### ISSUE TITLE
VRC-OSC Spotify Premium Controls

### ISSUE THREAD

**Issue by Alucard0504** [ShayBox/Spotify-VRChat-OSC#1]
Can you make a list of what the parameters are for use in the media controls? As well as what type are allowed? Could you maybe make a volume float if one doesn't exist already?

**Comment by ShayBox** [comment]
I support the parameters from the VRCOSC media prefab, I'll add a list
 https://github.com/VolcanicArts/VRCOSC/releases/tag/2023.109.0
